CU-25xk151: description with step environment variable keys
ChannelApe/channelape-typescript-sdk pull request #106
Opened 2022-01-28 13:09 UTC by kanhaiyas1088

2022-01-28 15:23 UTC, lmkerr commented on src/steps/service/StepsService.ts
> +const EXPECTED_POST_STATUS = 201;
should these just be an Enum at this point?

2022-01-28 16:50 UTC, ryankazokas requested changes
Just some minor feedback here @kanhaiyas1088 . Thanks for making these updates. Let me know when you are done making this feedback and I'll take one more look.

2022-01-28 16:50 UTC, ryankazokas commented on src/steps/service/StepsService.ts
>  const EXPECTED_GET_STATUS = 200;
Remove this if it's no longer needed here. It's scoped to this service so it should be fairly easy to update this.

2022-01-28 16:50 UTC, ryankazokas commented on src/steps/model/EnvironmentVariableKey.ts
> +  description: string;
Description is nullable. Can you add the optional flag via the question mark like in default value.

description?: string;

2022-01-31 13:12 UTC, ryankazokas approved these changes
Perfect. Thanks @kanhaiyas1088 for making these changes

2022-01-31 13:23 UTC, merged