Adds Api Account ID to sessions
ChannelApe/channelape-typescript-sdk pull request #81
Opened 2021-09-06 21:10 UTC by ryankazokas

API account private keys are just long lived sessions. When you make a request to get this session, the apiAccountId is the field populated since it's not associated with a specific user.

2021-09-07 14:27 UTC, mb-ca requested changes

2021-09-07 14:27 UTC, mb-ca commented on src/sessions/model/Session.ts
> +  apiAccountId: string;
@ryankazokas This field should be optional since a user request for a session does not return this property.

2021-09-07 14:27 UTC, mb-ca commented on package.json
> +  "version": "1.31.0-develop.0",
@ryankazokas Can you change to `1.30.0-develop.3` as we'll deploy both the step/supplier changes and this change in the same version (1.30.0)?

2021-09-09 19:22 UTC, ryankazokas commented
@mb-ca made your feedback suggestion and added a little more functionality I needed to be able to retrieve an API account 
https://docs.channelape.io/#0fc11098-aebb-4946-89b4-f2213feb43dd

2021-09-10 20:25 UTC, mb-ca approved these changes

2021-09-10 20:25 UTC, merged