Feature/update a locations sla information
ChannelApe/channelape-typescript-sdk pull request #98
Opened 2021-12-30 12:49 UTC by ManojKumarChannelApe

2022-01-03 09:04 UTC, akshay-channelape requested changes

2022-01-03 09:04 UTC, akshay-channelape commented on test/locations/service/LocationsService.spec.ts
> +        stack: 'some-error'
instead of `some-error` use `expectedChannelApeErrorResponse` and check of `404` error.

2022-01-03 09:04 UTC, akshay-channelape commented on test/locations/service/LocationsService.spec.ts
> +        expect(clientPutStub.args[0][0]).to
check for `statusCode` and `code` as well

2022-01-04 01:04 UTC, mb-ca requested changes

2022-01-04 01:04 UTC, mb-ca commented on src/locations/service/LocationsService.ts
> +      return this.mapResponseToPromise(requestUrl, deferred, error, response, body, this.EXPECTED_GET_OR_UPDATE_STATUS);
Similar to my comment of the closures PR, can you add a method to map the response to the LocationSLA object?

I noticed for the `getSla()` method it doesn't exist either, so please add in both methods and update the tests accordingly.

The only mapping which will be required is for the date fields:

```
LocationSLA
{
  createdAt: Date; // Map from ISO string to date
  fulfillmentSLAHours?: string;
  locationId: string;
  operatingDays: LocationSLAOperatingDay[];
  updatedAt: Date; // Map from ISO string to date
}
```
And be sure to loop through each LocationSLAOperatingDay in the array and do the same:

```
LocationSLAOperatingDay
{
  createdAt: Date; // Map from ISO string to date
  day: string;
  end: string;
  fulfillmentCutoffTime: string;
  id: string;
  open: string;
  updatedAt: Date; // Map from ISO string to date
}
```

2022-01-04 19:11 UTC, mb-ca commented
@ManojKumarChannelApe Last thing, can you update the readme to add a sample of this new update method below the "Get location SLA" description?

2022-01-05 18:22 UTC, merged